version: '3.8'

services:
  nfl-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MOTHERDUCK_TOKEN=${MOTHERDUCK_TOKEN}
      - PORT=8080
      - GIN_MODE=debug
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - nfl-network

networks:
  nfl-network:
    driver: bridge 